name: 'publish'

on:
  push:
    tags:
      - 'app-v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Apple Silicon (M1/M2/M3)
          - runner: 'macos-14'
            target: 'aarch64-apple-darwin'
          # Intel macOS
          - runner: 'macos-13'
            target: 'x86_64-apple-darwin'

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable) + targets (desktop + wasm)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }},wasm32-unknown-unknown

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install trunk & wasm-bindgen-cli (for Leptos WASM build)
        run: |
          cargo install trunk --locked || true
          cargo install wasm-bindgen-cli --locked || true

      - name: Build Leptos frontend (WASM) with trunk
        # Adjust the working-directory if your index.html/Cargo.toml live elsewhere.
        working-directory: .
        run: trunk build --release

      - name: Bundle app with Tauri (v2)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Force using Rust CLI instead of any Node tooling.
          tauriScript: cargo tauri build
          args: --target ${{ matrix.target }}
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
